site_name: Guides & Documentation
site_url: https://docs.digna.ai
theme:
  logo: assets/digna.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path         # breadcrumbs (Insiders gives extra options, but not required)
    - content.code.copy
    - search.highlight
    - search.share
    - navigation.indexes
nav:
  - Home:
      - Overview: home/overview.md
      - digna Data Anomalies:
          - Introduction: 'home/data_anomalies/Introduction.md'
      - digna Data Analytics:
          - Introduction: home/data_analytics/Introduction.md
      - digna Data Timeliness:
          - Introduction: home/data_timeliness/Introduction.md
      - digna Data Validation:
          - Introduction: home/data_validation/Introduction.md
      - digna Data Schema Tracker:
          - Introduction: 'home/schema_tracker/Introduction.md'
  - Gettings Started: 
          - How to create a data project: getting_started/how_to_create_project.md
          - How to connect a database to data project: getting_started/how_to_connect_database_to_data_project.md
          - How to add a datasource to project: getting_started/how_to_add_a_datasource_to_project.md
  - Integration: 
      - Databases:
          - Azure Synaps: databases/azure_synapse_connector_guide.md
          - Databricks: databases/databricks_connector_guide.md          
          - Databricks Legacy: databases/databricks_legacy_connector_guide.md          
          - Hive: databases/hive_connector_guide.md    
          - Netezza: databases/netezza_connector_guide.md
          - Oracle: databases/oracle_connector_guide.md
          - PostgreSQL: databases/postgres_connector_guide
          - Snowflake: databases/snowflake_connector_guide.md
          - MS SQL Server: databases/sqlserver_connector_guide.md
          - Teradata: databases/teradata_connector_guide.md
  - CLI Reference:
          - Introduction: cli/Introduction.md
          - Release 2025.09: cli/Command_Line_Interface_202509.md
          - Release 2025.04: cli/Command_Line_Interface_202504.md
          - Release 2024.12: cli/Command_Line_Interface_202412.md
          - Release 2024.11: cli/Command_Line_Interface_202411.md
          - Release 2024.09: cli/Command_Line_Interface_202409.md

  - Changelog: 
          - Release 2025.09: changelog/Release_202509.md
          - Release 2025.04: changelog/Release_202504.md
          

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list             # lets us add .md-button, .cards, .grid in Markdown
  - toc:
      permalink: true   # adds link icons to headings
      toc_depth: 3      # only show 2 levels (H1 + H2)#

extra_css:
  - style/extra.css