site_name: Documentation | Data Quality & Data Observability Platform
site_author: digna.ai
site_url: https://docs.digna.ai
theme:
  language: en
  logo: assets/digna.png
  favicon: assets/favicon.png
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.path         # breadcrumbs (Insiders gives extra options, but not required)
    - content.code.copy
    - search.highlight
    - search.share
    - navigation.indexes
nav:
  - "": index.md
  - Platform:
      - Overview: platform/overview.md
      - digna Data Anomalies:
          - Introduction: platform/data_anomalies/Introduction.md
      - digna Data Analytics:
          - Introduction: platform/data_analytics/Introduction.md
      - digna Data Timeliness:
          - Introduction: platform/data_timeliness/Introduction.md
      - digna Data Validation:
          - Introduction: platform/data_validation/Introduction.md
      - digna Data Schema Tracker:
          - Introduction: platform/schema_tracker/Introduction.md
  - Getting Started:
      - First steps:
          - How to create a data project: getting_started/how_to_create_project.md
          - How to connect a database to data project: getting_started/how_to_connect_database_to_data_project.md
          - How to add a datasource to project: getting_started/how_to_add_a_datasource_to_project.md
      - Scheduling:
          - How to schedule a daily job: getting_started/how_to_schedule_a_daily_job.md
          - How to use crontab definition: getting_started/how_to_use_crontab.md
  - Integration:
      - Databases:
          - Azure Synaps: databases/azure_synapse_connector_guide.md
          - Databricks: databases/databricks_connector_guide.md
          - Databricks Legacy: databases/databricks_legacy_connector_guide.md
          - Hive: databases/hive_connector_guide.md
          - Netezza: databases/netezza_connector_guide.md
          - Oracle: databases/oracle_connector_guide.md
          - PostgreSQL: databases/postgres_connector_guide.md
          - Snowflake: databases/snowflake_connector_guide.md
          - MS SQL Server: databases/sqlserver_connector_guide.md
          - Teradata: databases/teradata_connector_guide.md
  - CLI Reference:
          - Introduction: cli/Introduction.md
          - Release 2025.09: cli/Command_Line_Interface_202509.md
          - Release 2025.04: cli/Command_Line_Interface_202504.md
          - Release 2024.12: cli/Command_Line_Interface_202412.md
          - Release 2024.11: cli/Command_Line_Interface_202411.md
          - Release 2024.09: cli/Command_Line_Interface_202409.md

  - Changelog:
          - Release 2025.09: changelog/Release_202509.md
          - Release 2025.04: changelog/Release_202504.md
          - Release 2024.12: changelog/Release_202412.md

#extra:
#  alternate:
#    - name: English
#      link: /
#      lang: en
#    - name: Deutsch
#      link: /de/
#      lang: de

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list             # lets us add .md-button, .cards, .grid in Markdown
  - toc:
      permalink: true   # adds link icons to headings
      toc_depth: 3      # only show 2 levels (H1 + H2)#

extra_css:
  - style/extra.css

# --- SEO & Performance ---
plugins:
  - search
  - ultralytics:
      add_desc: true
      add_image: true
      add_keywords: true
  - i18n:
      docs_structure: folder
      languages:

        - locale: "en"
          name: English
          default: true
          build: true

        - locale: "de"
          name: Deutsch
          build: true
          nav_translations:
            Platform: Plattform
            Databases: Datenbanken
            Introduction: Einführung
            How to schedule a daily job: Wie man einen täglichen Job schedult
            How to use crontab definition: Wie man eine Crontab-Definition verwendet
            How to create a data project: Wie man ein Datenprojekt erstellt
            How to connect a database to data project: Wie man eine Datenbank mit einem Datenprojekt verbindet
            How to add a datasource to project: Wie man eine Datenquelle zu einem Projekt hinzufügt
            Getting Started: Erste Schritte
            First Steps: Erste Schritte
            Scheduling: Scheduling
            Integration: Integration
            CLI Reference: CLI Doku

        - locale: "pl"
          name: Polski
          build: true
          nav_translations:
            Platform: Platforma
            Databases: Bazy danych
            Introduction: Wprowadzenie
            How to schedule a daily job: Jak zdefiniować codzienne zadanie w harmonogramie
            How to use crontab definition: Jak używać definicji crontab
            How to create a data project: Jak utworzyć projekt danych
            How to connect a database to data project: Jak połączyć bazę danych z projektem danych
            How to add a datasource to project: Jak dodać źródło danych do projektu
            Getting Started: Pierwsze kroki
            First Steps: Pierwsze kroki
            Scheduling: Harmonogram
            Integration: Integracja
            CLI Reference: Dokumentacja CLI

        - locale: "fr"
          name: Français
          build: true
          nav_translations:
            Platform: Plateforme
            Databases: Bases de données
            Introduction: Introduction
            How to schedule a daily job: Comment programmer une tâche quotidienne
            How to use crontab definition: Comment utiliser une définition crontab
            How to create a data project: Comment créer un projet de données
            How to connect a database to data project: Comment connecter une base de données à un projet de données
            How to add a datasource to project: Comment ajouter une source de données à un projet
            Getting Started: Premiers pas
            First Steps: Premières étapes
            Scheduling: Planification
            Integration: Intégration
            CLI Reference: Référence CLI


        - locale: "es"
          name: Español
          build: true
          nav_translations:
             Platform: Plataforma
             Databases: Bases de datos
             Introduction: Introducción
             How to schedule a daily job: Cómo programar una tarea diaria
             How to use crontab definition: Cómo usar una definición de crontab
             How to create a data project: Cómo crear un proyecto de datos
             How to connect a database to data project: Cómo conectar una base de datos a un proyecto de datos
             How to add a datasource to project: Cómo añadir una fuente de datos a un proyecto
             Getting Started: Primeros pasos
             First Steps: Primeros pasos
             Scheduling: Programación
             Integration: Integración
             CLI Reference: Referencia CLI

